feat: about page
js-machine/js-machine-app pull request #10
Opened 2019-07-13 13:15 UTC by 1MrSmith

2019-07-13 13:16 UTC, 1MrSmith commented
![](https://github.trello.services/images/mini-trello-icon.png) [Landing Page (About page)](https://trello.com/c/OakMc1vX/11-landing-page-about-page)

2019-07-15 13:35 UTC, vharadkou requested changes

2019-07-15 13:35 UTC, vharadkou commented on js_machine_front/src/components/TileContent.tsx
> +            for (let i = 0; i < 3; i++) {
use arrTiles.map instead of for

2019-07-15 13:37 UTC, 1MrSmith commented on js_machine_front/src/components/TileContent.tsx
> +            for (let i = 0; i < 3; i++) {
Ok

2019-07-15 17:54 UTC, 1MrSmith commented on js_machine_front/src/components/TileContent.tsx
> +            for (let i = 0; i < 3; i++) {
fix

2019-07-16 13:57 UTC, vharadkou requested changes

2019-07-16 13:57 UTC, vharadkou commented on js_machine_front/src/components/TileContent.tsx
> +              key={i}
don't use index as a key, put some id

2019-07-16 14:53 UTC, 1MrSmith commented on js_machine_front/src/components/TileContent.tsx
> +              key={i}
fix

2019-07-16 14:54 UTC, vharadkou approved these changes

2019-07-16 14:54 UTC, merged