feat: closing the sidebar after clicking on a menu item
js-machine/js-machine-app pull request #31
Opened 2019-08-23 20:03 UTC by idzeravianka

2019-08-23 20:05 UTC, idzeravianka commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sidebar should close after navigation (mobile)](https://trello.com/c/1W1tGieI/36-sidebar-should-close-after-navigation-mobile)

2019-08-25 06:52 UTC, vharadkou requested changes

2019-08-25 06:52 UTC, vharadkou commented on js_machine_front/src/components/navBar/navBar.tsx
> +    if (this.state.menuIsOpened) {
consider to use this.setState(state => ({menuIsOpened: !state.menuIsOpened}));

2019-08-25 06:52 UTC, vharadkou commented on js_machine_front/src/components/navBar/models/navBar.ts
> +    menuIsOpened: boolean;
please rename to menuOpened

2019-08-25 06:52 UTC, vharadkou commented on js_machine_front/src/components/navBar/navBar.tsx
> +  handlingMenu = () => {
rename to handleMenu

2019-08-25 17:22 UTC, vharadkou approved these changes

2019-08-28 13:56 UTC, js-machine approved these changes

2019-08-28 13:56 UTC, js-machine commented on js_machine_front/src/components/navBar/navBar.tsx
> +  public state: NavBarState = { menuOpened: false };
isMenuOpened

2019-08-28 15:04 UTC, merged