Add main comp
js-machine/js-machine-app pull request #7
Opened 2019-07-12 16:03 UTC by idzeravianka

added main component

2019-07-12 16:17 UTC, vharadkou requested changes

2019-07-12 16:17 UTC, vharadkou commented on js_machine_front/src/components/RecentEvents.tsx
> +const RecentEvents: React.FC<any> = (props) => {
don't use any

2019-07-12 16:17 UTC, vharadkou commented on js_machine_front/src/routes/Main.tsx
> +import LinkToSicials from '../components/LinkToSocials';
use imports without '../' just 'components/LinksToSocials'

2019-07-12 16:19 UTC, vharadkou requested changes

2019-07-12 16:19 UTC, vharadkou commented on js_machine_front/src/styles/linkToSocials.css
> +.imgStyle {
use kebab-case for naming

2019-07-12 16:19 UTC, vharadkou commented on js_machine_front/src/styles/recentEvents.css
> +.recentEvents__post{
kebab-case

2019-07-12 16:20 UTC, vharadkou commented
![](https://github.trello.services/images/mini-trello-icon.png) [Landing Page (Main page)](https://trello.com/c/BvPRUVzc/8-landing-page-main-page)

2019-07-13 14:19 UTC, idzeravianka commented
![](https://github.trello.services/images/mini-trello-icon.png) [Landing Page (Main page)](https://trello.com/c/BvPRUVzc/8-landing-page-main-page)

2019-07-15 13:40 UTC, vharadkou requested changes

2019-07-15 13:40 UTC, vharadkou commented on js_machine_front/src/components/LinkToSocials.tsx
> +const LinkToSocials: React.FC = () => {
don't use default export, always export const at the beginning

2019-07-15 13:40 UTC, vharadkou commented on js_machine_front/src/components/LinkToSocials.tsx
> +const LinkToSocials: React.FC = () => {
use memo for component

2019-07-15 13:40 UTC, vharadkou commented on js_machine_front/src/components/RecentEvents.tsx
> +const RecentEvents: React.FC<Props> = (props: Props) => {
the same, default, memo

2019-07-15 14:52 UTC, vharadkou requested changes

2019-07-15 14:52 UTC, vharadkou commented on js_machine_front/src/routes/Main.tsx
> +        <RecentEvents test={testPosts} />
please rename test props to events

2019-07-15 14:53 UTC, vharadkou commented on js_machine_front/src/components/LinkToSocials.tsx
> +export const LinkToSocials: React.FC = memo(() => {
rename to SocialLinks

2019-07-15 14:53 UTC, vharadkou commented on js_machine_front/src/components/LinkToSocials.tsx
> +export const LinkToSocials: React.FC = memo(() => {
and all related styles

2019-07-17 08:43 UTC, vharadkou approved these changes

2019-07-17 08:44 UTC, merged