feat: added snow
js-machine/js-machine-app pull request #71
Opened 2019-12-15 03:29 UTC by vladimir-sviridenko

2019-12-15 03:29 UTC, vladimir-sviridenko commented
![](https://github.trello.services/images/mini-trello-icon.png) [{feat} Add Christmas team](https://trello.com/c/WJz47L3x/80-feat-add-christmas-team)

2019-12-15 10:17 UTC, DrJekill352 approved these changes

2019-12-20 07:23 UTC, vharadkou requested changes

2019-12-20 07:23 UTC, vharadkou commented on apps/js-machine-front/src/app/components/Snowflakes.tsx
> +    const getCanvasElementById = (id: string): HTMLCanvasElement => {
useCallback hook for function creation

2019-12-20 07:23 UTC, vharadkou commented on apps/js-machine-front/src/app/components/Snowflakes.tsx
> +    const getCanvasRenderingContext2D = (canvas: HTMLCanvasElement): CanvasRenderingContext2D => {
useCallback hook for function creation

2019-12-20 07:23 UTC, vharadkou commented on apps/js-machine-front/src/app/components/Snowflakes.tsx
> +    function startSnowflakes() {
useCallback hook for function creation

2019-12-20 07:23 UTC, vharadkou requested changes

2019-12-20 07:23 UTC, vharadkou commented on apps/js-machine-front/src/app/components/Snowflakes.tsx
> +        startSnowflakes();
you can create useSnowflakes hook and incapsulate all logic inside

2019-12-21 15:08 UTC, vharadkou requested changes

2019-12-21 15:08 UTC, vharadkou commented on apps/js-machine-front/src/app/components/Snowflakes.tsx
> +    const useStyles = makeStyles({
please create useStyles variable outside component, otherwise this variable will be create on each component Render

2019-12-21 15:08 UTC, vharadkou commented on apps/js-machine-front/src/app/components/Snowflakes.tsx
> +            <div className='snow-switcher'>
please use styles that you created by makeStyles, the same for all className

2019-12-21 15:08 UTC, vharadkou commented on apps/js-machine-front/src/app/components/styles/snowflakes.css
> +#snow {
please relocate styles to makeStyles function

2019-12-21 15:08 UTC, vharadkou commented on apps/js-machine-front/src/app/components/styles/snowflakesMedia.css
> +@media screen and (min-width: 960px) {
you can add media by css-in-js, please relocate it inside makeStyles function,
if you need an example, you can find code with 'theme.breakpoints.'

2019-12-22 12:28 UTC, vharadkou approved these changes

2019-12-23 20:02 UTC, merged