feat: add list of partners component
js-machine/js-machine-app pull request #9
Opened 2019-07-13 12:54 UTC by idzeravianka

2019-07-13 14:18 UTC, idzeravianka commented
![](https://github.trello.services/images/mini-trello-icon.png) [Landing Page (Partners Page)](https://trello.com/c/dl34uS1q/13-landing-page-partners-page)

2019-07-15 13:37 UTC, vharadkou requested changes

2019-07-15 13:37 UTC, vharadkou commented on js_machine_front/src/routes/Partners.tsx
> +      <div className="body">
body classname? maybe this should be partners?

2019-07-15 13:38 UTC, vharadkou requested changes

2019-07-15 13:38 UTC, vharadkou commented on js_machine_front/src/components/PartnersLogo.tsx
> +const PartnersLogo: React.FC = () => {
use memo

2019-07-15 13:38 UTC, vharadkou commented on js_machine_front/src/components/PartnersLogo.tsx
> +export default PartnersLogo;
don't use default export, always export const at the beginning

2019-07-15 14:48 UTC, vharadkou approved these changes

2019-07-15 14:50 UTC, merged